BaseURL: 'https://example.org/'
LanguageCode: "en"

Theme: lithium
ThemesDir: ../../

# Site Title
Title: Vidush H. Namah

Paginate: 12

# googleAnalytics: G-XXX

PERMALINKS:
  Post: /a/:slug/
  Page: /:slug/

PARAMS:
  Image: default.png
  Avatar: default.png
  Author: "John Smith"

  Directory:
    Blog: "articles"
  
  Articles:
    Dateformat: "2006.01.02"

  Themes:
    Toggle: true
    Default: dark
  
  Footer:
    Since: 2014

RELATED:
  IncludeNewer: true
  Threshold: 60
  ToLower: false
  Indices:
    - Name: series
      Weight: 100

Markup:
  # Code previews settings
  Highlight:
    NoClasses: true
    CodeFences: true
    GuessSyntax: true
    TabWidth: 4
    LineNoStart: 1
    LineNos: true

Youtube:
  PrivacyEnhanced: true

TAXONOMIES:
  Series: series

LANGUAGES:
  EN:
    MENU:
      Main:
      - Name: Home
        URL: /
        Weight: 10

      - Name: Gallery
        URL: /gallery
        Weight: 20

      - Name: About
        URL: /about
        Weight: 30
      
      Social:
      - Name: GitHub
        URL: https://github.com/vnsnippets

      - Name: LinkedIn
        URL: https://linkedin.com/in/vnamah

      - Name: Instagram
        URL: https://instagram.com/the.frame.drops
        
    PARAMS:
      Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."
      Keywords: [ "Sample", "Technology", "Photography" ]
      Translations:
        FooterMessage: Orion Next (Mauritius)
        DefaultArticlesMessage: NO CONTENT AVAILABLE
        RelatedContentHeader: Related Content