baseURL: 'https://orion-next--hydrogen.web.app'
languageCode: "en-gb"

title: "Vidush H. Namah"

theme: lithium
themesDir: ../../

paginate: 12

# googleAnalytics: G-XXX

permalinks:
  Post: /a/:slug/
  Page: /:slug/

params:
  meta:
    description: "Experience seamless design and innovative features tailored for success in the digital landscape."
    keywords: [ "Technology", "Photography" ]
    image: "/images/meta-image.png"
    avatar: "/images/avatar.png"
    author: "Vidush H. Namah"

  directory:
    blog: "articles"
  
  articles:
    dateformat: "2006.01.02"

  themes:
    toggle: true
    default: dark
  
  footer:
    Since: 2014

  features:
    widgets: false

  ## Supported target: self, blank
  social:
    - id: github
      name: GitHub
      url: https://github.com/vnsnippets
      icon: github.svg

    - id: linkedin
      name: LinkedIn
      url: https://linkedin.com/in/vnamah
      icon: linkedin.svg

    - id: instagram
      name: Instagram
      url: https://instagram.com/vnsnippets
      icon: instagram.svg

    - id: photography
      name: Photography
      url: /photography
      icon: camera.svg
      target: self

    - id: about
      name: About
      url: /about
      icon: info.svg
      target: self

menu:
  main: []

related:
  includenewer: true
  threshold: 60
  toLower: false
  indices:
    - name: series
      weight: 100

markup:
    goldmark:
        renderer:
            unsafe: false
    # tableOfContents:
    #     endLevel: 4
    #     ordered: true
    #     startLevel: 3
    highlight:
      noClasses: true
      codeFences: true
      guessSyntax: true
      tabWidth: 4
      lineNoStart: 1
      lineNos: true

youtube:
  privacyEnhanced: true

taxonomies:
  series: series